export default {
  DEFAULT_LANGUAGE: 'fr_FR',
  DEFAULT_CURRENCY: 'EUR',
  DEFAULT_COUNTRY: 'FR',
  DEFAULT_TOKEN_DURATION: '1d',
  REMEMBER_ME_TOKEN_DURATION: '15d',
  IMAGE_FILE_TYPES: ['jpg', 'png', 'jpeg'],
  DOCUMENT_FILE_TYPES: ['pdf'],
  MEDIA_FILE_TYPES: ['mp3', 'mp4'],
  MAX_IMAGE_FILE_SIZE: '2mb',
  MAX_DOCUMENT_FILE_SIZE: '5mb',
  MAX_MEDIA_FILE_SIZE: '8mb',
}
